apiVersion: v1
kind: Service
metadata:
  name: gd2574-inference-service
spec:
  selector:
    app: mnist-inference
  ports:
  - protocol: TCP
    port: 80             # External port
    targetPort: 5000     # Flask app internal port
  type: LoadBalancer
